export const authActionTypes = {
  SIGN_IN: 'auth/SIGN_IN',
  SIGN_IN_SUCCESS: 'auth/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'auth/SIGN_IN_FAILURE',
  SIGN_UP: 'auth/SIGN_UP',
  SIGN_UP_SUCCESS: 'auth/SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'auth/SIGN_UP_FAILURE',
  SIGN_OUT: 'auth/SIGN_OUT',
  SIGN_OUT_SUCCESS: 'auth/SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'auth/SIGN_OUT_FAILURE',
  GET_USER_INFO: 'auth/GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'auth/GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'auth/GET_USER_INFO_FAILURE',
};

export const loadingActionTypes = {
  START_LOADING: 'loading/START_LOADING',
  FINISH_LOADING: 'loading/FINISH_LOADING',
};

export const itemActionTypes = {
  GET_ITEMS: 'item/GET_ITEMS',
  GET_ITEMS_SUCCESS: 'item/GET_ITEMS_SUCCESS',
  GET_ITEMS_FAILURE: 'item/GET_ITEMS_FAILURE',
  ADD_ITEM: 'item/ADD_ITEM',
  ADD_ITEM_SUCCESS: 'item/ADD_ITEM_SUCCESS',
  ADD_ITEM_FAILURE: 'item/ADD_ITEM_FAILURE',
  REMOVE_ITEM: 'item/REMOVE_ITEM',
  REMOVE_ITEM_SUCCESS: 'item/REMOVE_ITEM_SUCCESS',
  REMOVE_ITEM_FAILURE: 'item/REMOVE_ITEM_FAILURE',
  MODIFY_ITEM: 'item/MODIFY_ITEM',
  MODIFY_ITEM_SUCCESS: 'item/MODIFY_ITEM_SUCCESS',
  MODIFY_ITEM_FAILURE: 'item/MODIFY_ITEM_FAILURE',
  LIKE_ITEM: 'item/LIKE_ITEM',
  LIKE_ITEM_SUCCESS: 'item/LIKE_ITEM_SUCCESS',
  LIKE_ITEM_FAILURE: 'item/LIKE_ITEM_FAILURE',
};

export const recommendActionTypes = {
  GET_WEATHER_INFO: 'recommend/GET_WEATHER_INFO',
  GET_WEATHER_INFO_SUCCESS: 'recommend/GET_WEATHER_INFO_SUCCESS',
  GET_WEATHER_INFO_FAILURE: 'recommend/GET_WEATHER_INFO_FAILURE',
  GET_RECOMMENDATION_LIST: 'recommend/GET_RECOMMENDATION_LIST',
  GET_RECOMMENDATION_LIST_SUCCESS: 'recommend/GET_RECOMMENDATION_LIST_SUCCESS',
  GET_RECOMMENDATION_LIST_FAILURE: 'recommend/GET_RECOMMENDATION_LIST_FAILURE',
};
